import pg from "pg";
import dotenv from "dotenv";
dotenv.config();
const { Client } = pg;

const SQL = `
  CREATE TABLE objects (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    x_start INT NOT NULL,
    x_end INT NOT NULL,
    y_start INT NOT NULL,
    y_end INT NOT NULL
  );

  CREATE TABLE users (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  score INT NOT NULL);

  INSERT INTO objects
  (name, x_start, x_end, y_start, y_end)
  VALUES
  ('umbrella', 290, 330, 390, 610),
  ('bottlecap', 195, 240, 680, 710),
  ('dart-board', 810, 870, 310, 380);
`;

const SQLdropAll = `
  DROP TABLE IF EXISTS objects, users;
`;

(async function populate() {
  console.log("Population database with dummy data...");

  const client = new Client({
    connectionString: process.env.postgresString,
  });
  await client.connect();
  await client.query(SQLdropAll);
  await client.query(SQL);
  await client.end();

  console.log("FInished populating database");
})();
